# Generated by Django 4.1.6 on 2025-11-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('director', models.CharField(max_length=25, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
