# Generated by Django 4.1.6 on 2025-11-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelisFantasia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('director', models.CharField(max_length=25, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PelisFiccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('director', models.CharField(max_length=25, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('contraseña', models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='PelisDrama',
        ),
    ]
